# Generated by Django 5.1.7 on 2025-03-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minscribe_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
