# Generated by Django 5.1.7 on 2025-03-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minscribe_blog', '0003_post_has_livestream_post_has_poll_post_has_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50, unique=True), unique=True),
        ),
    ]
