# Generated by Django 5.1.7 on 2025-03-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minscribe_blog', '0004_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cognitiveprofile',
            name='learning_style',
            field=models.CharField(choices=[('Visual', 'Visual'), ('Auditory', 'Auditory'), ('Reading/Writing', 'Reading/Writing'), ('Kinesthetic', 'Kinesthetic')], max_length=50),
        ),
    ]
