# Generated by Django 5.1.7 on 2025-03-28 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minscribe_blog', '0006_quiz_end_date_quizquestion_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubmissionError',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField()),
                ('error_type', models.CharField(max_length=100)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minscribe_blog.quiz')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minscribe_blog.user')),
            ],
            options={
                'unique_together': {('user_id', 'quiz_id')},
            },
        ),
    ]
