# Generated by Django 5.1.7 on 2025-03-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minscribe_blog', '0007_quizsubmissionerror'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizSubmissionError',
            new_name='QuizSubmission',
        ),
    ]
