# Generated by Django 5.1.7 on 2025-03-28 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minscribe_blog', '0008_rename_quizsubmissionerror_quizsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='choice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='minscribe_blog.quizquestion'),
        ),
    ]
