# Generated by Django 5.1.7 on 2025-04-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minscribe_blog', '0010_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='markdown_content',
            field=models.TextField(blank=True),
        ),
    ]
