# Generated by Django 5.1.7 on 2025-04-19 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minscribe_blog', '0012_post_created_at_post_is_collaborative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_posts', to='minscribe_blog.user'),
        ),
        migrations.AlterField(
            model_name='collaborationinvite',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inviter', to='minscribe_blog.user'),
        ),
        migrations.AlterUniqueTogether(
            name='collaborationinvite',
            unique_together={('post', 'invitee')},
        ),
    ]
