# Generated by Django 5.1.7 on 2025-04-19 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minscribe_blog', '0013_post_original_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('version_number', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minscribe_blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minscribe_blog.user')),
            ],
        ),
    ]
